name: core
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# author: izadalab <dhytodev@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  rxdart:
  http:
  moor:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  moor_generator:
  build_runner:
